project:
  type: book
  output-dir: docs

book:
  title: "Mastering Shiny Book Club"
  author: "Lucio Cornejo"
  date: "08/01/2022"
  output-file: "Mastering-Shiny-Book-Club"
  highlight-style: github
  sidebar:
    style: docked
    background: light
    tools:
      - icon: github
        href: "https://github.com/lucio-cornejo/Mastering-Shiny_Bookclub"
  search:
    location: navbar
    type: overlay # textbox or overlay
  page-footer: 
    background: light
    left:
      "R-Ladies Lima"
  chapters:
    - index.qmd
    - part: "Sesi贸n 1"
      chapters:
        - chapter_01.qmd
        - chapter_02.qmd
    - part: "Sesi贸n 2"
      chapters:
        - chapter_03.qmd
    - part: "Sesi贸n 3"
      chapters:
        - chapter_06.qmd
        - chapter_09.qmd
    - part: "Sesi贸n 4"
      chapters:
        - chapter_NULL.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc-title: Tabla de contenidos
    theme:
      - lux
      - slate
      - theme.scss
    include-in-header: scripts.html
    code-copy: true
    code-link: true
  pdf:
    documentclass: scrreprt



